---
title: "Executive Summary"
csl: ecosystem-services.csl
fontsize: 12pt
output:
  bookdown::word_document2:
    toc: yes
    number_sections: yes
font: timesnewroman
subtitle: Teesta Riverine Ecosystem
bibliography: references.bib
always_allow_html: yes
---

## Introduction
The world's rivers not only affect the planet's physical landscape, but they also have an impact on the well-being of billions of people worldwide. Rivers supply ecosystem goods including as fish, drinking water, and wildlife, as well as services such as boating and swimming. Rivers that flow freely add to the aesthetic and recreational value of the region, resulting in increased property values for those who live near them. In addition, free-flowing rivers help to dilute waste water discharges, protecting water quality. Rivers are also important habitats for endangered and vulnerable species [@Richardson2009]. When anthropogenic activities reach a sustainable level, rivers' potential to deliver such ecosystem goods and services is reduced.

The plant life in the Teesta river basin is varied. Around 4000 plant species bloom in the basin. In the Teesta basin of Sikkim, 3418 species of angiosperms and gymnosperms have been discovered. However, more than 50 plant species have become endangered throughout time, according to the IUCN. Dennstaedlia elwesu (Dennstaedtcaceae) and Zeuxine pulchra (Orchidaceae) are extinct, 10 species are endangered, and 18 are rare. Endangered plants like Zeuxine pulchra have become extinct, with just six of nine living. There are 169 mammal species and 689 butterfly species in the Teesta basin. Several reptile species (for example, pit vipers, skinks, and Himalayan agamids) are uniquely found in Sikkim and the Eastern Himalayas. The snow toad (Scutiger sikkimensis), as well as numerous species of Paa, are unique to the region. The number of butterfly species is larger at higher and lower elevations. The Red Panda is listed as endangered by the IUCN, whereas the marbled cat is only found in the Teesta river basin's Chungthang area.

The total hydroelectric power potential of India is estimated to be 84 GW. Sikkim has a potential share of 2.9 percent, or around 4.29 GW. The Central Electricity Authority of India issued a preliminary feasibility study on the building of 162 new hydroelectric projects totaling more than 50,000 MW in 2004. This plan includes ten projects in Sikkim, with a total installed capacity of 1,469 MW [@CEA2015]. Sikkim has a total hydroelectricity potential of 5,325 MW, which is spread throughout various stages of development [@EDPS2020]. Currently, 15 projects are in various stages of construction, and all of them must be completed by the end of 2018, according to the Draft National Electricity Plan 2018. Several dams on the Teesta River and its tributaries may accelerate earthquakes and increase damage. Earthquakes have been recorded in Dzongu and Chungthang. When an earthquake struck Sikkim on September 18, 2011, it was alleged that 16 workers died while working on the Teesta III hydropower project. Furthermore, on August 13, 2016, a huge landslide in the Dzongu region of North Sikkim halted the passage of the Kanaka river near Mantam. Hydroelectric plant construction can frequently result in a scarcity of drinking water. Water scarcity has increased as a result of the disappearance of springs/streams. Dams have also impeded natural river flow and reduced downstream river levels. Other issues that residents living near construction sites face include traffic congestion, accidents, and deaths. While cultural encroachment is a major issue highlighted by natives in the case of migration. Historically, the Lepcha people have organised large protests throughout the construction of comparable development projects. Agricultural productivity appears to be changing at the project sites as well. The rate of pulse generation looked to be decreasing with time. As a result, there is an urgent need to assess the restoration advantages of the Teesta Riverine Ecosystem for long-term sustainability and the conservation of a diverse range of flora and animals.

## Objectives of the study
The study's goals are as follows: 
1. To understand the socioeconomic profile of the people of Sikkim and to analyse livelihood patterns and changes as a result of the development of hydropower projects.
1. To comprehend the effects of hydropower projects in the upper basin of the Teesta River on various issues such as natural ecosystems, culture, livelihoods, and river water quality.
1. To estimate the non-market benefits of river Teesta restoration in the Sikkim Himalaya and to evaluate the transferability of welfare estimates.

## Data and methods
Samples were collected from numerous villages and small towns around the Teesta River, the Teesta Stage V dam, and the Teesta Stage V powerhouse for the study. The villages were chosen for their proximity to the Teesta River and dams, so that the influence could be seen. Dikchu lies around 3 kilometres from the Teesta Stage V dam, making it a suitable site for the survey. Makha, around 10 kilometres from the Teesta V dam, is another noteworthy sample hamlet. Among the several villages affected by the Teesta Stage V dam and the Teesta Stage V Powerhouse in Sirwani are Bardang, Majitar, Mamring, Manglay, Rangpo, and Singtam. Purposive sampling was used to choose the sample based on its geographic location and proximity to the Teesta River, the Teesta Stage V dam, and the Teesta Stage V powerhouse. Following the selection of villages, sample households were picked at random in each village. The questionnaire was pre-tested in each community. The questionnaire was pre-tested by interviewing 5 homes in each hamlet, for a total of 45 households. A hypothetical river restoration project was the subject of an open-ended Willingness-to-Pay (WTP) question on the pre-test questionnaire. The primary survey included a willingness-to-pay (WTP) item with a double-bounded dichotomous choice (DBDC).

The questionnaire was painstakingly crafted after careful analysis of the Teesta River's numerous aspects, including its ecological, economic, and other socio-cultural significance. The questionnaire was conceptually focused on assessing information on the socioeconomic profile of the households, water availability and consumption behaviour, impact of hydroelectric projects on agricultural lands (if owned) and people's livelihood, perception of impact on water and wild habitat, environment, culture, and the river itself, and identification of ecosystem services or benefits. The WTP question was a double bounded dichotomous choice (DBDC) kind. The DCchoice package in the R software is used to analyse the data. The package's dbchoice() function may estimate the logistic, normal, log logistic, and log-normal distributions. Furthermore, the DCchoice package contains two methods for constructing confidence intervals for WTP estimates, krCI() and bootCI(). The krCI() function uses the simulation methodology outlined by [@Krinsky1986] to generate confidence intervals, whereas bootCI() uses the bootstrap method.

## Findings
The median age of the respondents is 41 years. Approximately 53% of those questioned were males, while 47% were women. Looking at the respondents' educational backgrounds, we can see that 40% had elementary education, 39% had secondary education, 11% had upper secondary education, 7% had a graduate degree, and 3% had a master's degree (3.1 percent ). It may be inferred that around 80% of the heads of households were married, 15% were still single, and the remaining were either widowed (3.4%) or separated (1.7 percent ). The variable employ is a categorical variable that captures the various vocations or employment patterns of the households. Only 7% of the households in the sample were farmers, and a corresponding 6.5 percent worked in government.
47 percent and 46 percent of the dwellings in the sample fell into the second (10001 - 20000) and first (Nil - 10000) categories, respectively.
This is followed by 4.8 percent in the third group and 2.9 percent in the fifth.
The variable community refers to the many communities that dwell in the sample villages, such as the Bhutias, Lepchas, Nepalis, and other minority groups. It is noteworthy to note that just around 1.2 percent and 1.7 percent of the indigenous people of Sikkim, the Lepchas and Bhutias, respectively, dwell in the sample villages. Tamang, Limbu, Chettri, Gurung, Pradhan, Bengalis, Ekka, Dahal, and other ethnic groups made up the rest 97 percent of the population. This subcommunity is part of a bigger Nepali community.

54 percent of families owned property, 33 percent rented, while the remaining 12 percent lived on wooded land, government of Sikkim property, leases, or the ‘koot' system. The 'koot' system is comparable to a lease system, although tenants may also provide in-kind payments. Each household member has resided in the area for an average of 30 years. The variable period, which indicates the duration of the households' existence in the hamlet, reflects this. The median household spending in the sample is INR 8000.00. According to the statistics, 92 percent of families have private restrooms in their homes.Approximately 22% of the sample households were migrants. In most cases, individuals had come from the neighbouring state of West Bengal to work as unskilled labourers at HEP projects in Darjeeling, Kalimpong, Alipurduar, Siliguri, and Jalpaiguri. In the Teesta River, 90 percent of the families participate in religious activities. The river is usually utilised for funeral rituals. Approximately 75% of respondents are unsatisfied with the Teesta River's current state. The respondents were displeased with the Teesta River's changing water level as a result of dam construction. Respondents were also concerned about the river's visual attractiveness, fish availability, and the recent increase in quarrying operations.

Dams earn a grade of 3 from roughly 35% of respondents, indicating their significance to the economic side of life, livelihood, jobs, and infrastructure supplied. Similarly, 25% rated 2, 15% rated 0, and fewer than 10% scored 1, suggesting that dams are unimportant to certain individuals. Overall, they seek to create a balance between growth and Teesta River preservation/restoration. Households were also asked if they had witnessed any significant landslides in their region. Landslides, according to the responses, are not a major issue on a regular basis, and they just disturb normal living but are not life threatening. Nepali is the most frequently spoken language, and the majority of families belong to either the General group (which includes a lesser number of native Sikkimese) or the Other Backward Class (OBC). The most frequent cooking fuels in the sample households are gas (LPG) and firewood. Chickens, cows, and goats are among the most popular farm animals among the people. The HEP had no visible influence on the agricultural lands of the peasants. Households have a generally good attitude about water quality. Only during the monsoon season can water become murky owing to excessive rain and the accompanying overflow of springs conveying debris and silt. The availability of fish in the river, the link of some type of cultural identity with the river, the reduction in noise pollution from the dams, and the loss of picnic areas along the river banks were the most commonly recognised values and attributes for the river Teesta. Respondents said that they would not be able to find enough fish due to the river's changing water level.

According to the DBDC logistic model projections, families that rank the HEPs highly place a higher value on employment and other economic advantages than on river Teesta restoration benefits. If a family owns agricultural land along the river, they must be willing to pay for the river's restoration. The flood mitigation benefit seen by the family from river restoration would be the basis for such a decision. Even households that have rented property for irrigation, the variable ownershipRented, are prepared to pay for river restoration in exchange for the same flood protection advantage that these households would obtain and so avoid losing the land. The proportion of the expenditure is also significant and positive, implying that households with higher monthly expenditures are willing to pay for the river’s restoration. Household members who are in informal business, works in a shop, sells food in the market, works in a private company, is a casual worker or is unemployed are less likely to pay for the restoration of the river as compared to the farmers and government employees.

The logistic distribution estimates are also comparable to the normal distribution estimates. The estimated model, like the logistic model, has converged. Rating, ownership, experience, employability, and satisfaction are all important and have the same relationship with WTP as in the previous model. The only difference is that the median WTP estimate of INR 393 is higher. The Krinsky-Robb method's median WTP estimate has a 95 percent confidence range of INR 363 to INR 420. The median and 95 percent CI values in the logistic distribution are narrower than in the normal distribution. The important variables from the regression model were chosen for the benefit transfer estimations, and their coefficients and related mean values were computed in accordance with [@Johnston2015]. The computed tranferable value of WTP is INR 232.44, which reflects per family readiness to pay for river Teesta rehabilitation. In the absence of the original study data, this estimate may be translated to an approximate ecosystem service value for the indicated policy change. The percentage transfer error in this study is 61.98 percent. This is the benefit function value transfer, which is more well regarded in the benefit transfer literature [@Barton2002].

## References